### ISSUE TITLE
Does this run on Windows?

### ISSUE THREAD

**Issue by ghost** [se-asr/model#1]
Hello! Tried getting this to run on Windows (unfortunately I do not have Linux as of right now). What I did was the following:

- Pip installed DeepSpeech in my Conda env 
- Downloaded the following files: All binaries, one trie, one output graph
- Merged the binaries into one file
- Decompressed trie and merged binary file
- Renamed the decompressed files according to the line "deepspeech --model output_graph.pb --lm lm.binary --trie lm.trie --audio myfile.wav"

I get the following error:
`usage: deepspeech [-h] --model MODEL [--scorer SCORER] --audio AUDIO                                                [--beam_width BEAM_WIDTH] [--lm_alpha LM_ALPHA]                                                   [--lm_beta LM_BETA] [--version] [--extended] [--json]                                             [--candidate_transcripts CANDIDATE_TRANSCRIPTS]                  
               deepspeech: error: ambiguous option: --lm could match --lm_alpha, --lm_beta `

When testing either of these instead of --lm, I get the following error:
`usage: deepspeech [-h] --model MODEL [--scorer SCORER] --audio AUDIO                                                [--beam_width BEAM_WIDTH] [--lm_alpha LM_ALPHA]                                                   [--lm_beta LM_BETA] [--version] [--extended] [--json]                                             [--candidate_transcripts CANDIDATE_TRANSCRIPTS]                          
       deepspeech: error: argument --lm_beta: invalid float value: 'lm.binary' `

What does this error mean? Did I do something wrong in the steps? I couldn't clearly understand all steps. Does this even run on windows? Do I need to download the source code?

**Comment by hsson** [comment]
Make sure you're running exactly version `v0.6.1` of deepspeech! I think they changed a lot around how language models were loaded in version `v0.7.0` and above!

If they doesn't help I'll take another look. 

It should run fine on windows as far as I know, but I haven't tested it myself.
