### ISSUE TITLE
Update example to latest version of DeepSpeech 0.9.3

### ISSUE THREAD

**Issue by buzzy** [se-asr/model#3]
What's the correct CLI command to run your stuff on version 0.9.3?

**Comment by hsson** [comment]
Unfortunately the model was made for a specific version of DeepSpeech, and it's very uncertain how straightforward it would be to port the model to a new version. Simply updating the example is not sufficient as the model binaries are incompatible. Unfortunately neither of us authors have enough time to work on this, I'm thus closing this issue.
